//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpayeeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxBrackekt
    {
        public int Bracket_Id { get; set; }
        public double First_Bracket { get; set; }
        public double Second_Bracket { get; set; }
        public double Third_Bracket { get; set; }
        public double Fourth_Bracket { get; set; }
        public double Fifth_Bracket { get; set; }
    }
}
