//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpayeeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxSlab
    {
        public int Slab_Id { get; set; }
        public decimal First_Slab { get; set; }
        public decimal Second_Slab { get; set; }
        public decimal Third_Slab { get; set; }
        public decimal Fourth_Slab { get; set; }
        public bool Married { get; set; }
    }
}
